services:
  next-ts-app:
    image: next-ts-app
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: next-ts-app
    volumes:
      - ./app:/app/app
      - ./public:/app/public

    # Set environment variables directly in the docker-compose file
    #environment:
    #DATABASE_URL: 'mysql://root:password@mysql-db:3306'

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      mysql-db:
        condition: service_started
    restart: always

  mysql-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextapp
    restart: always
