services:
  next-ts-app:
    image: next-ts-app
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: next-ts-app
    volumes:
      - ./app:/app/app
      - ./public:/app/public
    environment:
      DATABASE_URL: DATABASE_URL="mysql://root:password@nextapp:3306
    ports:
      - '3000:3000'
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextapp
    restart: always
